---
- hosts: k8s
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: docker-ce
      state: installed
#  - name: write the apache config file
#    template:
#      src: /srv/httpd.j2
#      dest: /etc/httpd.conf
#    notify:
#    - restart apache
#  - name: ensure apache is running
#    service:
#      name: httpd
#      state: started
#  handlers:
#    - name: restart apache
#      service:
#       name: httpd
#       state: restarted
